POST http://localhost:8080/quotes HTTP/1.1
content-type: application/json

{
	"symbol":"BA",
	"price":500.0,
	"availableVolume":2000,
	"expiration":"2022-12-31"
}

###
POST http://localhost:8080/quotes HTTP/1.1
content-type: application/json

{
    "id":"408bae47-c6a9-4133-937a-a3ee06621169",
	"symbol":"AARP",
	"price":200.0,
	"availableVolume":3000,
	"expiration":"2022-12-31"
}
###
POST http://localhost:8080/quotes/trade?symbol=AAPL&volumeRequested=500
###
GET http://localhost:8080/quotes
###
GET http://localhost:8080/quotes/symbol/AAPL

###
GET http://localhost:8080/quotes/best/BA

###
PUT http://localhost:8080/quotes HTTP/1.1
content-type: application/json

{
    "id":"408bae47-c6a9-4133-937a-a3ee06621169",
	"symbol":"AARP",
	"price":215.0,
	"availableVolume":3000,
	"expiration":"2022-12-31"
}

###
DELETE http://localhost:8080/quotes/id/408bae47-c6a9-4133-937a-a3ee06621169
###
DELETE http://localhost:8080/quotes/symbol/BA